# Generated by Django 3.2.4 on 2021-06-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('patente', models.CharField(max_length=6)),
                ('anio_fabricacion', models.DecimalField(decimal_places=0, max_digits=4)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
            ],
        ),
    ]
